# Generated by Django 4.1.7 on 2023-05-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
                (
                    "profile_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("job", models.CharField(max_length=255)),
                (
                    "profile_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tv_series_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                (
                    "cast",
                    models.ManyToManyField(
                        related_name="tv_series_cast", to="movie_app.cast"
                    ),
                ),
                (
                    "crew",
                    models.ManyToManyField(
                        related_name="tv_series_view", to="movie_app.crew"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("status", models.CharField(max_length=30)),
                ("release_date", models.CharField(max_length=40)),
                ("popularity", models.FloatField()),
                ("poster_path", models.CharField(max_length=200)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("tagline", models.CharField(blank=True, max_length=200, null=True)),
                ("budget", models.IntegerField()),
                ("revenue", models.IntegerField()),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                (
                    "cast",
                    models.ManyToManyField(
                        related_name="movies_cast", to="movie_app.cast"
                    ),
                ),
                (
                    "crew",
                    models.ManyToManyField(
                        related_name="movies_crew", to="movie_app.crew"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movies_genre", to="movie_app.genre"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="genre",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre",
                to="movie_app.movie",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_members",
                to="movie_app.movie",
            ),
        ),
        migrations.AddField(
            model_name="cast",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast_members",
                to="movie_app.movie",
            ),
        ),
    ]
