# Generated by Django 4.1.7 on 2023-06-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="crew",
        ),
        migrations.RemoveField(
            model_name="tv",
            name="crew",
        ),
        migrations.DeleteModel(
            name="Crew",
        ),
    ]
