# Generated by Django 4.1.7 on 2023-06-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_remove_movie_crew_remove_tv_crew_delete_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="tv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast_members",
                to="movie_app.tv",
            ),
        ),
        migrations.AddField(
            model_name="genre",
            name="tv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_tv",
                to="movie_app.tv",
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="first_air_date",
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="genres",
            field=models.ManyToManyField(related_name="tv_genre", to="movie_app.genre"),
        ),
        migrations.AddField(
            model_name="tv",
            name="last_air_date",
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="number_of_episodes",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="number_of_seasons",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="popularity",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="poster_path",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="status",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="vote_average",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tv",
            name="vote_count",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cast",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast_members",
                to="movie_app.movie",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre",
                to="movie_app.movie",
            ),
        ),
    ]
