# Generated by Django 4.1.7 on 2023-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0009_review_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(max_length=3000),
        ),
    ]
