# Generated by Django 4.1.7 on 2023-06-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0010_alter_review_review_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_text",
            new_name="comment",
        ),
    ]
