# Generated by Django 4.1.7 on 2023-06-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0011_rename_review_text_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie_app.review"
            ),
        ),
    ]
