# Generated by Django 4.1.7 on 2023-06-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0014_tv_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="url",
        ),
    ]
